# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F3wHN8eP-tDO0baaqOudwL7eRyh9r_qh
"""

import pandas as pd
import json
from IPython.display import display, HTML, clear_output
import ipywidgets as widgets
from google.colab import auth
import gspread
from google.auth import default

# --- 1. CONFIGURACIÓN Y AUTH ---
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

BOLD_MAGENTA = "#FF0040"
BOLD_NAVY = "#170F49"

def limpiar_monto_pro(valor):
    """Limpia montos manejando inconsistencias de miles y decimales latam/US"""
    if pd.isna(valor) or str(valor).strip() in ["", "0", "0.0", "-"]:
        return 0.0
    s = str(valor).replace('$', '').replace('S/.', '').replace(' ', '').strip()
    if '.' in s and ',' in s:
        if s.rfind('.') < s.rfind(','): s = s.replace('.', '').replace(',', '.')
        else: s = s.replace(',', '')
    elif ',' in s: s = s.replace(',', '.')
    try: return round(float(s), 2)
    except: return 0.0

# --- 2. MOTOR DE ANÁLISIS SIN MIX % ---
def mostrar_vista_previa(b=None):
    f_ini = pd.to_datetime(wdg_inicio.value)
    f_fin = pd.to_datetime(wdg_fin.value)
    analisis_web = {}

    with output_area:
        clear_output()
        display(HTML(f"<h2 style='color:{BOLD_NAVY};'>💎 bold | Análisis Financiero Consolidado</h2>"))

        try:
            sh = gc.open("Financial Position")
            pestañas = {
                "Resumen Posición Financiera CF": "Bold_CF",
                "Resumen Posición Financiera CO SAS": "Bold_SAS",
                "Bold Perú": "Bold_Peru"
            }

            for p_nombre, p_id in pestañas.items():
                ws = sh.worksheet(p_nombre)
                data = ws.get_all_values()

                # Encontrar encabezado
                idx_h = next(i for i, row in enumerate(data) if "Fecha" in row)
                df = pd.DataFrame.from_records(data[idx_h+1:], columns=data[idx_h])
                df.columns = [str(c).strip() for c in df.columns]
                df['Fecha'] = pd.to_datetime(df['Fecha'], dayfirst=True, errors='coerce')
                df = df.dropna(subset=['Fecha']).sort_values('Fecha')

                # Columnas de bancos
                cols_ignore = ['Fecha', 'Total', 'Saldo Total Soles', 'Variación', 'Saldo Total', '']
                cols_bancos = [c for c in df.columns if c not in cols_ignore and not c.startswith('Unnamed')]

                # Limpiar montos
                for c in cols_bancos:
                    df[c] = df[c].apply(limpiar_monto_pro)

                # Calcular total y FILTRAR solo días con saldos (ignora proyecciones vacías)
                df['Total_Empresa'] = df[cols_bancos].sum(axis=1)
                df_real = df[df['Total_Empresa'] > 0].copy()

                if not df_real.empty:
                    # Análisis para el JSON de la WEB
                    serie = df_real['Total_Empresa']
                    hoy_e = serie.iloc[-1]
                    ayer_e = serie.iloc[-2] if len(serie) > 1 else hoy_e
                    hace_7_e = serie.iloc[-8] if len(serie) > 7 else ayer_e

                    analisis_web[p_id] = {
                        "saldo_actual": hoy_e,
                        "d_1_variacion": ((hoy_e - ayer_e) / ayer_e * 100) if ayer_e != 0 else 0,
                        "d_7_variacion": ((hoy_e - hace_7_e) / hace_7_e * 100) if hace_7_e != 0 else 0,
                        "promedio_30d": serie.tail(30).mean(),
                        "min_30d": serie.tail(30).min(),
                        "max_30d": serie.tail(30).max()
                    }

                    # Tabla UI Colab (Sin Mix %)
                    df_f = df_real[(df_real['Fecha'] >= f_ini) & (df_real['Fecha'] <= f_fin)]
                    if not df_f.empty:
                        res_b = []
                        for b in cols_bancos:
                            actual_b = df_f[b].iloc[-1]
                            ayer_b = df_real[b].iloc[-2] if len(df_real) > 1 else 0
                            res_b.append({
                                "Banco": b,
                                "Saldo Actual": actual_b,
                                "Var. D+1 ($)": actual_b - ayer_b,
                                "Min (Periodo)": df_f[b].min(),
                                "Max (Periodo)": df_f[b].max()
                            })

                        df_res = pd.DataFrame(res_b).sort_values('Saldo Actual', ascending=False)
                        display(HTML(f"<div style='margin-top:15px; border-left:4px solid {BOLD_MAGENTA}; padding-left:10px;'><b>{p_nombre}</b></div>"))
                        display(df_res.style.format({
                            "Saldo Actual": "${:,.2f}", "Var. D+1 ($)": "${:,.2f}",
                            "Min (Periodo)": "${:,.2f}", "Max (Periodo)": "${:,.2f}"
                        }).map(lambda x: f"color: {'red' if x < 0 else 'green' if x > 0 else 'black'}", subset=["Var. D+1 ($)"]))

            with open('financial_data.json', 'w') as f:
                json.dump(analisis_web, f)
            display(HTML("<p style='color:green; font-weight:bold;'>✅ Análisis generado (Mix % eliminado).</p>"))

        except Exception as e:
            print(f"❌ Error: {e}")

# --- UI ---
wdg_inicio = widgets.DatePicker(description='Desde:', value=pd.Timestamp('2026-04-11'))
wdg_fin = widgets.DatePicker(description='Hasta:', value=pd.Timestamp('2026-05-12'))
btn_calc = widgets.Button(description='Ejecutar Análisis BI', button_style='info', icon='calculator')
btn_calc.on_click(mostrar_vista_previa)
output_area = widgets.Output()

display(widgets.VBox([
    widgets.HTML(f"<h1 style='color:{BOLD_MAGENTA}; font-family:sans-serif;'>Bold Financial Intelligence</h1>"),
    widgets.HBox([wdg_inicio, wdg_fin, btn_calc]),
    output_area
]))